import { Link, useParams } from 'react-router-dom'
import { AlertTriangle, ExternalLink, Info, Layers } from 'lucide-react'
import { CRITERIA_BY_ID } from '@/lib/catalog'
import {
  METHODOLOGY_BY_ID,
  METHODOLOGY_LAST_REVIEWED,
} from '@/lib/methodology'
import type { Transform } from '@/lib/types'
import { MethodologyLayout } from './MethodologyLayout'

/**
 * Per-criterion methodology page. Read at /methodology/:id.
 * Each section is intentionally self-contained so the page is deep-linkable
 * (e.g. share a colleague the exact NO₂ methodology).
 */
export function CriterionDetailPage() {
  const { id } = useParams<{ id: string }>()
  const criterion = id ? CRITERIA_BY_ID[id] : undefined
  const method = id ? METHODOLOGY_BY_ID[id] : undefined

  if (!criterion || !method) {
    return (
      <MethodologyLayout>
        <h1 className="mb-2 text-xl font-semibold">Criterion not found</h1>
        <p className="text-sm text-ink-secondary">
          The criterion id <code className="text-ink-primary">{id}</code> is
          not in the catalog. <Link to="/methodology" className="text-accent">View all criteria</Link>.
        </p>
      </MethodologyLayout>
    )
  }

  const transformBlurb = transformDescription(criterion.transform)

  return (
    <MethodologyLayout>
      <header className="mb-6">
        <div className="text-[10px] uppercase tracking-wider text-ink-muted">
          Criterion
        </div>
        <h1 className="mt-1 text-2xl font-semibold text-ink-primary">
          {criterion.displayName}
        </h1>
        <div className="mt-2 flex flex-wrap items-center gap-2 text-[11px] text-ink-secondary">
          <Pill>Unit · {criterion.unit}</Pill>
          <Pill>
            Direction ·{' '}
            {criterion.direction === 'more_is_better'
              ? 'more is better'
              : criterion.direction === 'less_is_better'
                ? 'less is better'
                : 'categorical'}
          </Pill>
          <Pill>Default weight · {criterion.defaultWeight} / 10</Pill>
          <Pill>
            Default {criterion.defaultEnabled ? 'enabled' : 'disabled'}
          </Pill>
          <Pill>Standardisation · {transformBlurb}</Pill>
        </div>
      </header>

      <Section heading="What it measures">
        <p>{method.whatItMeasures}</p>
      </Section>

      <Section heading="Why it matters">
        <p>{method.whyItMatters}</p>
      </Section>

      <Section
        heading="What we ship today (Phase 1.1 synthetic)"
        icon={<Layers className="h-4 w-4 text-accent" />}
      >
        <p>{method.phase1Estimation}</p>
        <p className="mt-2 text-xs text-ink-muted">
          The synthetic seed is regenerated by{' '}
          <code className="rounded bg-bg-subtle px-1 py-0.5">
            npm run seed
          </code>
          ; deterministic for byte-stable reproduction across runs.
        </p>
      </Section>

      <Section
        heading="Phase 2 sources (production pipeline)"
        icon={<Info className="h-4 w-4 text-accent" />}
      >
        <ul className="space-y-3">
          {method.realSources.map((src) => (
            <li
              key={src.url}
              className="rounded-md border border-border bg-bg-panel p-3"
            >
              <div className="flex items-start justify-between gap-2">
                <div className="min-w-0">
                  <a
                    href={src.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-1 text-sm font-medium text-accent hover:underline"
                  >
                    {src.name}
                    <ExternalLink className="h-3 w-3" />
                  </a>
                  <div className="mt-0.5 text-xs text-ink-secondary">
                    {src.publisher}
                  </div>
                </div>
              </div>
              <dl className="mt-2 grid grid-cols-1 gap-x-4 gap-y-1 text-[11px] sm:grid-cols-3">
                <SrcRow label="Licence" value={src.licence} />
                <SrcRow label="Cadence" value={src.cadence} />
                <SrcRow
                  label="Latest known release"
                  value={src.publisherLastKnown}
                />
              </dl>
            </li>
          ))}
        </ul>
      </Section>

      {method.caveats?.length ? (
        <Section
          heading="Caveats"
          icon={<AlertTriangle className="h-4 w-4 text-amber-400" />}
        >
          <ul className="list-disc space-y-1 pl-5 text-sm text-ink-secondary">
            {method.caveats.map((c, i) => (
              <li key={i}>{c}</li>
            ))}
          </ul>
        </Section>
      ) : null}

      <footer className="mt-8 border-t border-border pt-3 text-[11px] text-ink-muted">
        Content last reviewed {METHODOLOGY_LAST_REVIEWED}. Cited publisher
        dates reflect the freshest editions at authorship time; publishers
        will have moved on by the time you read this.
      </footer>
    </MethodologyLayout>
  )
}

function Section({
  heading,
  icon,
  children,
}: {
  heading: string
  icon?: React.ReactNode
  children: React.ReactNode
}) {
  return (
    <section className="mt-6">
      <h2 className="mb-2 flex items-center gap-1.5 text-sm font-semibold uppercase tracking-wider text-ink-secondary">
        {icon}
        <span>{heading}</span>
      </h2>
      <div className="text-sm leading-relaxed text-ink-primary">{children}</div>
    </section>
  )
}

function Pill({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-block rounded-md border border-border bg-bg-subtle px-2 py-0.5">
      {children}
    </span>
  )
}

function SrcRow({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="text-[10px] uppercase tracking-wider text-ink-muted">
        {label}
      </dt>
      <dd className="text-ink-primary">{value}</dd>
    </div>
  )
}

function transformDescription(t: Transform): string {
  // Light, human-readable spec line ("Fuzzy decay 5→30 min", etc.).
  switch (t.type) {
    case 'linear':
      return `Linear ${t.min} → ${t.max}`
    case 'fuzzy_decay':
      return `Fuzzy decay ${t.idealMax} → ${t.acceptableMax} (${t.curve})`
    case 'categorical': {
      const keys = Object.keys(t.mapping)
      return `Categorical (${keys.length} bands)`
    }
  }
}
